#!/usr/bin/env bun

import { CATPPUCCIN_FLAVOR_NAMES, createCatppuccinDesktopTheme } from "../src/theme/catppuccin"
import { CATPPUCCIN_FLAVORS } from "../src/theme/catppuccin-palette"
import { format } from "prettier"

const check = process.argv.includes("--check")
const files = CATPPUCCIN_FLAVOR_NAMES.map((flavor) => ({
  path: new URL(`../src/theme/themes/catppuccin-${flavor}.json`, import.meta.url),
  content: `${JSON.stringify(createCatppuccinDesktopTheme(flavor), null, 2)}\n`,
}))

// First paint and the runtime cache share a revision of the exact generated themes.
const preload = {
  revision: new Bun.CryptoHasher("sha256").update(files.map((file) => file.content).join("")).digest("hex"),
  themes: Object.fromEntries(
    CATPPUCCIN_FLAVOR_NAMES.map((flavor) => [
      `catppuccin-${flavor}`,
      { mode: flavor === "latte" ? "light" : "dark", background: CATPPUCCIN_FLAVORS[flavor].swatches.base },
    ]),
  ),
}
files.push({
  path: new URL("../src/theme/catppuccin-preload.ts", import.meta.url),
  content: await format(
    `// Generated by script/catppuccin.ts. Do not edit.\nexport const CATPPUCCIN_PRELOAD = ${JSON.stringify(preload)} as const\n`,
    { parser: "typescript", semi: false, printWidth: 120 },
  ),
})
const boot = new URL("../../app/public/oc-theme-preload.js", import.meta.url)
const source = await Bun.file(boot).text()
const marker = /  \/\/ BEGIN GENERATED CATPPUCCIN\n[\s\S]*?  \/\/ END GENERATED CATPPUCCIN/
if (!marker.test(source)) throw new Error("Missing Catppuccin preload generation markers")
files.push({
  path: boot,
  content: await format(
    source.replace(marker, `  // BEGIN GENERATED CATPPUCCIN\n  var catppuccin = ${JSON.stringify(preload)}\n  // END GENERATED CATPPUCCIN`),
    { parser: "babel", semi: false, printWidth: 120 },
  ),
})

const changed = (
  await Promise.all(
    files.map(async (file) => {
      const current = (await Bun.file(file.path).exists()) ? await Bun.file(file.path).text() : ""
      if (current === file.content) return null
      if (check) return file.path.pathname
      await Bun.write(file.path, file.content)
      return file.path.pathname
    }),
  )
).filter((file): file is string => file !== null)

if (changed.length === 0) {
  console.log("Desktop Catppuccin themes already synced")
  process.exit(0)
}

if (check) {
  console.error("Desktop Catppuccin themes are out of sync:")
  for (const file of changed) console.error(`- ${file}`)
  process.exit(1)
}

console.log("Updated desktop Catppuccin themes:")
for (const file of changed) console.log(`- ${file}`)
