#!/usr/bin/env bun

import { flavorEntries, version } from "@catppuccin/palette"
import { format } from "prettier"

const palette = Object.fromEntries(
  flavorEntries.map(([name, flavor]) => [
    name,
    {
      label: flavor.name,
      swatches: Object.fromEntries(flavor.colorEntries.map(([name, color]) => [name, color.hex])),
      ansi: Object.fromEntries(
        flavor.ansiColorEntries.flatMap(([name, color]) => [
          [name, color.normal.hex],
          [`bright${name.charAt(0).toUpperCase()}${name.slice(1)}`, color.bright.hex],
        ]),
      ),
    },
  ]),
)
const content = await format(
  `// Generated by script/catppuccin-palette.ts from @catppuccin/palette (MIT). Do not edit.
// https://github.com/catppuccin/palette
export const CATPPUCCIN_PALETTE_VERSION = ${JSON.stringify(version)}
export const CATPPUCCIN_FLAVORS = ${JSON.stringify(palette)} as const
`,
  { parser: "typescript", semi: false, printWidth: 120 },
)
const path = new URL("../src/theme/catppuccin-palette.ts", import.meta.url)
if ((await Bun.file(path).exists()) && (await Bun.file(path).text()) === content) {
  console.log("Official Catppuccin palette already synced")
  process.exit(0)
}
if (process.argv.includes("--check")) {
  console.error("Official Catppuccin palette is out of sync; run script/catppuccin-palette.ts")
  process.exit(1)
}
await Bun.write(path, content)
console.log("Updated official Catppuccin palette")
