// Generated by script/catppuccin.ts. Do not edit.
export const CATPPUCCIN_PRELOAD = {
  revision: "b2f7f929ddc0b71aeb78653fbb0e4f6906c0c4d010de890092b89bf0d621a112",
  themes: {
    "catppuccin-latte": { mode: "light", background: "#eff1f5" },
    "catppuccin-frappe": { mode: "dark", background: "#303446" },
    "catppuccin-macchiato": { mode: "dark", background: "#24273a" },
    "catppuccin-mocha": { mode: "dark", background: "#1e1e2e" },
  },
} as const
